### ISSUE TITLE
not accessible not found in win 10 

### ISSUE THREAD

**Issue by pleabargain** [binjospookie/--shots#14]
# How to reproduce
click start
search shots
does not return shots
## Expected behavior
find shots
## Actual behavior
no return
* Operating system;

win 10

* --shots version;
latest v of shots 2feb2017

![image](https://cloud.githubusercontent.com/assets/640846/22552766/4b9ae4fc-e96b-11e6-8943-45799a96faf0.png)

**Comment by binjospookie** [comment]
https://github.com/electron/electron/issues/8564

**Comment by binjospookie** [comment]
https://github.com/binjospookie/--shots/commit/376107b5baee8791dcb82cff7f29cfbdbf09b9dd
