### ISSUE TITLE
shots home folder?

### ISSUE THREAD

**Issue by orschiro** [binjospookie/--shots#16]
Dear @binjospookie,

What's the shots folder used for?

![image](https://cloud.githubusercontent.com/assets/170947/22586529/907d8b6e-e9fd-11e6-9324-47796ffc7b01.png)

**Comment by binjospookie** [comment]
Hello!
This folder used when you save your screenshot locally(default folder).

**Comment by orschiro** [comment]
I see. 

What if I always save my files to Desktop? Can I somehow prevent shots from creating this other folder?

![image](https://cloud.githubusercontent.com/assets/170947/22588612/e58b9dea-ea06-11e6-8860-a9cec6321958.png)

![image](https://cloud.githubusercontent.com/assets/170947/22588619/ee98113e-ea06-11e6-87dd-586a2d6ca1c6.png)

**Comment by binjospookie** [comment]
You can't do it from settings. But if you save locally using `Ctrl+L` you can choose dist folder for your screenshots.

I'll add ability to change default directory for saving!

**Comment by orschiro** [comment]
> I'll add ability to change default directory for saving!

Wow, great. Thank you! :-)

**Comment by binjospookie** [comment]
@orschiro in next release you could to remove `--shots` folder!
I don't think that there is a need to add to settings `default folder option`, cause --shots remember your last choosen folder(when you saving file locally).
But `--shots` folder is unnecessary. 
So... :)

**Comment by binjospookie** [comment]
https://github.com/binjospookie/--shots/commit/33aecd955f8de10b48e1c0d96ba8176aaf44322b

**Comment by orschiro** [comment]
Wow, perfect! :-)

When are you going to release the next deb package?

**Comment by binjospookie** [comment]
I plan to release a new version at these week

**Comment by orschiro** [comment]
Very cool!

I will see how I can spread the word about your app.
