### ISSUE TITLE
All your progress will be lost. Are you sure?

### ISSUE THREAD

**Issue by orschiro** [binjospookie/--shots#18]
Dear @binjospookie,

Please help me understand this following message: 

![image](https://cloud.githubusercontent.com/assets/170947/22589691/ca8d1406-ea0b-11e6-9ef7-8c34c1332034.png)

Why is it asking me this? I saved my previous screenshot and minimised shots back to tray. Why do I get this message?

Yours,

Robert

**Comment by binjospookie** [comment]
It prevents you from lost changes if you saved and continue draw.
It's OK with your saved screenshot. Just trying to prevent an error(^).

I know how to improve this point and do it in v1.0.5.

Thank you!

**Comment by orschiro** [comment]
Oh cool. So many exciting things to come with version 1.0.5. :-)

Yours,

Robert

**Comment by binjospookie** [comment]
Exciting for me too :smiley:

**Comment by binjospookie** [comment]
Fixed!
