### ISSUE TITLE
Google Docs: Conflicting shortcut Ctrl + alt + m to add comment

### ISSUE THREAD

**Issue by orschiro** [binjospookie/--shots#19]
Dear @binjospookie,

Any idea how to fix this?

![google-docs-peek](https://cloud.githubusercontent.com/assets/170947/22617841/b38e7c2c-eace-11e6-9924-a876d16c7074.gif)

**Comment by binjospookie** [comment]
Oh, I need to change to another shortcut. But I don't which  shortcut could be safe.
Maybe you know?

**Comment by orschiro** [comment]
That's indeed a tricky question. How about the following solution?

![disable-shortcuts](https://cloud.githubusercontent.com/assets/170947/22638905/97e5fb8e-ec4b-11e6-94c8-371743d3330d.png)

**Comment by binjospookie** [comment]
I'm not sure, that it's simple(don't forget about "Enable shortcuts" :-) ).
I'm searching for safe combination right now.

**Comment by orschiro** [comment]
Maybe a combination like Ctrl + Meta + Alt + M?

**Comment by binjospookie** [comment]
I think. that your first idea the most correct :)

**Comment by orschiro** [comment]
Which first idea? To disable the shortcut?

**Comment by binjospookie** [comment]
Yes!

**Comment by orschiro** [comment]
I am glad! I think it would be a nice addition! :-)

**Comment by binjospookie** [comment]
https://github.com/binjospookie/--shots/commit/122d30bbe6ebf32dd896d3e1dde20dc4d1a4cbe7

**Comment by orschiro** [comment]
That was quick! :+1:
