### ISSUE TITLE
Package for Arch Linux

### ISSUE THREAD

**Issue by AlejandroC90** [binjospookie/--shots#2]
Any plan of making an aur package for Arch Linux?

**Comment by binjospookie** [comment]
Hello! I don't know anything about Arch (but I heard that it's cool). 
There are some types:
* AppImage
* snap
* deb 
* rpm 
* freebsd 
* pacman 
* p5p
* apk.

Maybe, one of them could resolve your problem?

**Comment by AlejandroC90** [comment]
I don't know what you're asking exactly, But I can only recognize  and notice that "pacman" is Arch-linux packages manager.

**Comment by binjospookie** [comment]
I hope it works.

[shots-1.0.0.pacman](https://github.com/binjospookie/--shots/releases/download/v1.0.0/shots-1.0.0.pacman)
