### ISSUE TITLE
Copy to clipboard option

### ISSUE THREAD

**Issue by orschiro** [binjospookie/--shots#20]
Dear @binjospookie,

Another idea. :-)

In the final menu after you are done editing, can we add an option to "copy to clipboard" in addition to "Save" to disk?

Often, I don't actually need to save it to disk but quickly want to reuse it from the clipboard, e.g. to paste it into Github. :-)

Yours,

Robert

**Comment by binjospookie** [comment]
Hello! 
Good idea.

**Comment by orschiro** [comment]
I am glad you find it useful. :-)

**Comment by binjospookie** [comment]
![image](https://cloud.githubusercontent.com/assets/8722478/22692843/d824bdaa-ed51-11e6-8990-2fe39d5e69f8.png)

Just paste it :)

**Comment by orschiro** [comment]
Oh, cool! :-)

**Comment by orschiro** [comment]
Will this become part of the next release?

**Comment by binjospookie** [comment]
Yes.

**Comment by orschiro** [comment]
Thank you. :-)
