### ISSUE TITLE
Imgur support?

### ISSUE THREAD

**Issue by CHBMB** [binjospookie/--shots#24]
Would love to see an imgur upload option.  Any plans?

**Comment by binjospookie** [comment]
Good idea.

**Comment by CHBMB** [comment]
Fantastic, that would make this perfect for me.

**Comment by binjospookie** [comment]
@CHBMB you mean upload for anonymus or registered users?

**Comment by CHBMB** [comment]
@binjospookie My preference would be for my user account to be honest.  Not a fan of anonymous uploading.

**Comment by binjospookie** [comment]
@CHBMB you're right!

**Comment by CHBMB** [comment]
Awesome I can't wait!  Been using [screencloud](https://screencloud.net/) purely for the imgur upload facility, but --shots has some lovely editing features than will come in very useful.  If the link to the image can be copied to clipboard on upload that would really be the icing on the cake.  Sorry to be giving you so much work! ;)

**Comment by binjospookie** [comment]
We plan to release new --shots at this week :)

**Comment by CHBMB** [comment]
That soon?  Wow, I kind of imagined it would take a couple of months or so...

**Comment by binjospookie** [comment]
It's ready on 60-70% :)

**Comment by CHBMB** [comment]
Got to admit, I'm impressed.

**Comment by binjospookie** [comment]
@CHBMB :)

http://i.imgur.com/ANP8smN.png

**Comment by binjospookie** [comment]
v1.2.0 coming soon

**Comment by CHBMB** [comment]
@binjospookie lol love the link!

**Comment by CHBMB** [comment]
Works perfectly!  Brilliant
