### ISSUE TITLE
Cannot change from pen to text

### ISSUE THREAD

**Issue by orschiro** [binjospookie/--shots#26]
Dear @binjospookie,

I cannot change from pen to text. 

Please see the following animation. 

I am using version 1.2.

Yours,

Robert

**Comment by orschiro** [comment]
https://www.youtube.com/watch?v=XZ5WL7DruPk&feature=youtu.be

**Comment by orschiro** [comment]
And maybe related, I cannot use text at all. 

It's not letting me write anything.

**Comment by Groxot** [comment]
@orschiro can you use text from menu bar?

**Comment by orschiro** [comment]
@Groxot yes!

**Comment by Gaserd** [comment]
@orschir

**Comment by binjospookie** [comment]
@orschiro Hello!
It looks like perfomance bug. I'm not sure, that we can fix it in current version of --shots. We are planning to rewrite app and main point is perfomance. Tomorrow we meet with guys and will talk about it :)

**Comment by orschiro** [comment]
OK, thanks for your prompt feedback! :-)
