### ISSUE TITLE
Not working using Gnome and Wayland.

### ISSUE THREAD

**Issue by CHBMB** [binjospookie/--shots#33]
# How to reproduce

Run a Linux Gnome desktop using Wayland instead of X 

## Expected behavior

Screenshots work

## Actual behavior

Just get a black screeen

* Operating system:

Antergos Gnome using Wayland

* --shots version:

V1.2.0

FWIW I think this is a Wayland problem rather than a --shots issue, but logging it here just in case others are wondering.... 

Should probably add I've changed from LightDM to GnomeDM on Antergos.  Pretty sure LightDM is still using X, but changing to GDM uses Wayland.

**Comment by binjospookie** [comment]
@CHBMB thank you for your investigation!

**Comment by CHBMB** [comment]
I've tried a fresh reinstall of my OS using LightDM and that works so even more sure now the issue is Wayland.

**Comment by CHBMB** [comment]
@binjospookie So with the move towards Wayland as the desktop protocol on Linux, will --shots work in the future?  Or has this been closed as you don't intend to support Wayland?

**Comment by orschiro** [comment]
@binjospookie same question as @CHBMB. Tried shots on Fedora 27 which uses Wayland but it's not working. Only showing a black screen when taking a screenshots. Are you going to support Wayland which soon is becoming the replacement for Xorg?
