### ISSUE TITLE
Windows 10 2+ screens bug

### ISSUE THREAD

**Issue by binjospookie** [binjospookie/--shots#4]
On Windows 10 --shots make 1 monitor screenshot.

**Comment by binjospookie** [comment]
Need test with Electron 1.4.10

**Comment by binjospookie** [comment]
@alexeyvax could you help try to resolve this problem? I haven't Windows. Especially WIndows 10.

**Comment by sigmanor** [comment]
yeah weird, it's make screenshot only of second monitor

**Comment by alexeyvax** [comment]
I don`t use windows, I use Linux too. Soryan:)

**Comment by binjospookie** [comment]
Damn. Ok, I'll try to find a machine with Win10.

**Comment by binjospookie** [comment]
Maybe @yanlobat could fix that? :grimacing:
